# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
    - name: Set up MySQL
      uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '8.0'
    - run: |
        mysql -uroot -h127.0.0.1 -e \
        "CREATE DATABASE student_mobility CHARACTER SET utf8mb4 \
        COLLATE utf8mb4_0900_ai_ci;"
    - run: |
        mysql -uroot -h127.0.0.1 -e \
        "CREATE USER 'student_mobility'@'localhost' IDENTIFIED BY 'secret';";
    - run: |
        mysql -uroot -h127.0.0.1 -e \
        "GRANT ALL privileges ON student_mobility.* TO 'student_mobility'@'localhost';"
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      working-directory: ./server
    - name: Codecov
      uses: codecov/codecov-action@v5.5.1

  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '23'
      - run: yarn install
        working-directory: ./client-eu
      - run: yarn build
        working-directory: ./client-eu
      - run: yarn test
        working-directory: ./client-eu
